### ISSUE TITLE
The configuration area at '/home/developer/.eclipse/org.eclipse.platform_4.7.0_1473617060_linux_gtk_x86_64/configuration' could not be created. 

### ISSUE THREAD

**Issue by Xysto** [DrSnowbird/eclipse-photon-docker#2]
Hi !
I've that error in a graphical window when I run the run.sh script:

`The configuration area at '/home/developer/.eclipse/org.eclipse.platform_4.7.0_1473617060_linux_gtk_x86_64/configuration' could not be created.  Please choose a writable location using the '-configuration' command line option.`

I've modified the baseDataFolder variable in the script but that's all. The new path is still in my home directory. Can it be the problem ?

**Comment by Xysto** [comment]
I've started the container in interactive mode with bash to identify the problem and it comes from the .eclipse and eclipse-workspace directories in the container are owned by root et not by developer. I resolved the problem in interactive mode but it's dirty ^^. How can I fix this directly in your image ? (I'm very new with docker).

**Comment by DrSnowbird** [comment]
Hi there!
I update Dockerfile and clean up / change directory owners to developers.
Could you try again in your environment? Thanks. 
I tested on clean Ubuntu 16.04 and ok. But, I would appreciate that you can let me know if you still have the problem.

**Comment by Xysto** [comment]
It run smoothly now :smiley:. Thanks a lot!

**Comment by DrSnowbird** [comment]
Thanks for letting me know. You are most welcomed!

**Comment by DrSnowbird** [comment]
You are welcomed!
